version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - YANDEX_API_TOKEN=${YANDEX_API_TOKEN}
      - YANDEX_ORGANIZATION_ID=${YANDEX_ORGANIZATION_ID}
      - ALLOWED_USERNAME=${ALLOWED_USERNAME}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_COLLECTION_NAME=${MONGO_COLLECTION_NAME}
      - TRACKER_QUEUE=${TRACKER_QUEUE}
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data:
